/* TeleVerso Educativo · Complemento del campo formativo Lenguajes · PPA 1
   Agrega las 10 misiones de "Voces que cuentan" sin eliminar las actividades existentes. */
(() => {
  // Etiquetar el contenido existente para conservarlo como otro campo formativo.
  if (missionCatalog.m1) { missionCatalog.m1.field = 'ens'; missionCatalog.m1.fieldTitle = 'Ética, Naturaleza y Sociedades'; }
  if (missionCatalog.m2) { missionCatalog.m2.field = 'ens'; missionCatalog.m2.fieldTitle = 'Ética, Naturaleza y Sociedades'; }

  Object.assign(missionCatalog, {
    len1:{id:'len1',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R1 · Radar de afirmaciones',type:'lang-classify',icon:'🔎',desc:'Distingue datos verificables, opiniones argumentables y estereotipos sobre lenguas y culturas.',paper:'Cuaderno p. 5',cats:['Dato verificable','Opinión / argumento','Estereotipo / prejuicio'],items:[
      ['En una fuente escolar se explica que las lenguas transmiten identidad y sentido de pertenencia.',0,'Puede comprobarse consultando la fuente.'],
      ['Todas las personas que hablan una lengua originaria piensan igual.',2,'Generaliza y borra la diversidad de las personas.'],
      ['Usar una lengua en la escuela puede contribuir a mantenerla viva.',1,'Es una postura que debe sostenerse con razones y evidencias.'],
      ['En el proyecto se elaborarán un debate, una exposición y un folleto.',0,'Es información explícita del PPA.'],
      ['Una lengua vale más si la habla un mayor número de personas.',2,'Confunde cantidad de hablantes con valor cultural.'],
      ['La tecnología puede ayudar a difundir prácticas culturales, aunque el acceso no es igual para todas las personas.',1,'Es una afirmación razonable que puede argumentarse con fuentes.'],
      ['Una tradición pierde automáticamente su valor cuando cambia.',2,'Presenta el cambio cultural como algo necesariamente negativo.'],
      ['Un argumento sólido necesita razones y datos que lo respalden.',0,'Es una característica trabajada en los textos argumentativos.'] ]},
    len2:{id:'len2',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R2 · Argumento en cuatro piezas',type:'lang-quiz',icon:'🧩',desc:'Reconoce tesis, evidencia, razonamiento y propuesta para construir argumentos más sólidos.',paper:'Cuaderno p. 11',qs:[
      ['¿Cuál funciona mejor como tesis para un debate?',['Las lenguas existen.','Valorar y usar las lenguas originarias fortalece la identidad y la diversidad cultural.','Me gustan algunas palabras.'],1,'Una tesis adopta una postura clara que puede defenderse.'],
      ['¿Cuál es la evidencia más pertinente?',['“Yo creo que sí”.','Una fuente explica que la discriminación y el desplazamiento reducen el uso de lenguas originarias.','“Todos lo saben”.'],1,'La evidencia debe poder rastrearse y relacionarse con la tesis.'],
      ['¿Qué hace el razonamiento?',['Conecta la evidencia con la tesis y explica por qué la respalda.','Decora la tarjeta.','Repite la tesis sin explicar.'],0,'El razonamiento muestra la relación lógica entre evidencia y postura.'],
      ['¿Cuál es una propuesta realizable?',['Obligar a todas las personas a aprender una lengua.','Incluir palabras, relatos o mensajes bilingües verificados con hablantes en actividades escolares.','Esperar a que el problema desaparezca.'],1,'Una propuesta debe ser viable, respetuosa y vinculada con la comunidad.'],
      ['En un texto argumentativo, ¿qué suele aparecer al final?',['La conclusión que reafirma o revisa la postura.','Una lista sin relación.','Sólo el título.'],0,'La conclusión recupera la postura después de los argumentos.'] ]},
    len3:{id:'len3',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R3 · Debate cultural: decide y responde',type:'lang-quiz',icon:'🎙️',desc:'Elige intervenciones que usan evidencias, escuchan objeciones y evitan descalificaciones.',paper:'Cuaderno p. 14',qs:[
      ['Tu compañero afirma: “Si una lengua cambia, ya dejó de ser auténtica”. ¿Qué respuesta es más útil?',['“Estás mal”.','Preguntar qué evidencia sostiene esa idea y señalar que las lenguas se transforman históricamente.','Cambiar de tema.'],1,'Debatir implica cuestionar ideas con razones, no atacar personas.'],
      ['¿Qué tarjeta fortalece mejor una postura?',['Tesis + evidencia rastreable + explicación de su relación.','Una frase muy grande sin fuente.','Una imagen sin pie.'],0,'La tarjeta comparativa debe ayudar a sostener y contrastar argumentos.'],
      ['Si escuchas una objeción razonable, lo mejor es…',['ignorarla.','reformular tu argumento o reconocer un límite.','hablar más fuerte.'],1,'Un argumento puede mejorar al responder objeciones.'],
      ['¿Qué conducta cuida el diálogo?',['Respetar turnos y resumir lo que entendiste antes de responder.','Interrumpir para ganar tiempo.','Burlarse del acento.'],0,'La escucha activa es parte del diálogo argumentativo.'],
      ['¿Qué pregunta abre pensamiento crítico?',['¿Quién tiene la culpa?','¿Qué prácticas favorecen o dificultan que una lengua siga usándose y qué evidencias tenemos?','¿Cuál lengua es la mejor?'],1,'La pregunta permite investigar causas, prácticas y evidencias.'] ]},
    len4:{id:'len4',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R4 · Memorama pluricultural',type:'lang-memory',icon:'🧠',desc:'Relaciona conceptos clave con su explicación: identidad, diversidad, desplazamiento, revitalización y más.',paper:'Cuaderno p. 18',pairs:[
      ['Diversidad lingüística','Existencia y convivencia de distintas lenguas y variantes.'],['Identidad','Sentido de quiénes somos y de pertenencia a un grupo o comunidad.'],['Interculturalidad','Diálogo respetuoso entre culturas que cuestiona desigualdades.'],['Desplazamiento lingüístico','Reducción del uso de una lengua frente a otra con mayor poder o prestigio.'],['Revitalización','Acciones para ampliar el uso y transmisión de una lengua.'],['Pluriculturalidad','Presencia y convivencia de múltiples culturas.'],['Práctica cultural','Acción o costumbre con significados compartidos en una comunidad.'],['Tejido social','Relaciones y vínculos entre personas que construyen vida en común.'] ]},
    len5:{id:'len5',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R5 · Curador de expresiones',type:'lang-quiz',icon:'🎨',desc:'Relaciona decisiones artísticas con propósitos de una exposición pluricultural.',paper:'Cuaderno p. 19',qs:[
      ['Quieres mostrar distintas voces de la comunidad. ¿Qué decisión ayuda más?',['Incluir una sola perspectiva.','Combinar testimonios, imágenes y expresiones artísticas con créditos y contexto.','Quitar toda explicación.'],1,'Una exposición pluricultural hace visibles perspectivas diversas y su contexto.'],
      ['Una pieza aborda un problema social. ¿Qué cédula conviene?',['Nombre de la pieza, intención, técnica y fuente o testimonio.','Sólo “bonito”.','Una fecha inventada.'],0,'La cédula permite comprender la pieza y rastrear su contexto.'],
      ['¿Qué uso del arte se relaciona con el tejido social?',['Abrir espacios de diálogo y representar perspectivas diversas.','Ocultar conflictos.','Repetir estereotipos.'],0,'El arte puede favorecer empatía, crítica y diálogo.'],
      ['Antes de representar una práctica cultural ajena conviene…',['preguntar, investigar y evitar caricaturizarla.','inventar símbolos.','copiar una imagen sin fuente.'],0,'Investigar y dialogar reduce errores y apropiaciones irrespetuosas.'],
      ['¿Qué mejora la accesibilidad de la exposición?',['Única explicación escrita con letra pequeña.','Opciones visuales y orales, circulación posible y textos legibles.','Cerrar preguntas al público.'],1,'Diversificar formas de acceso amplía la participación.'] ]},
    len6:{id:'len6',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R6 · Ruta de exposición',type:'lang-sequence',icon:'🧭',desc:'Ordena los pasos para preparar una exposición comunitaria clara, segura y participativa.',paper:'Cuaderno p. 21',items:['Investigar una expresión cultural y dialogar con personas que la conocen.','Elegir qué aspecto se representará y qué mensaje se quiere comunicar.','Diseñar o crear la experimentación artística.','Redactar una cédula con contexto, técnica, intención y fuente.','Planear espacio, recorrido, tiempos y responsabilidades.','Revisar accesibilidad, seguridad y respeto cultural.','Ensayar la explicación y ajustar el montaje.','Presentar, escuchar comentarios y registrar mejoras.']},
    len7:{id:'len7',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R7 · Semáforo de difusión',type:'lang-quiz',icon:'🚦',desc:'Valora decisiones para compartir prácticas culturales en medios escolares o digitales.',paper:'Cuaderno p. 24',qs:[
      ['Publicar una fotografía de una ceremonia sin permiso ni contexto…',['Verde: siempre ayuda.','Amarillo/rojo: requiere permiso, contexto y cuidado.','No importa.'],1,'Difundir no significa exponer a personas o prácticas sin consentimiento.'],
      ['Compartir una palabra en lengua originaria confirmando escritura, significado y crédito con una persona hablante…',['Es una práctica responsable.','Es innecesario verificar.','Debe traducirse de cualquier manera.'],0,'La verificación y el crédito cuidan el sentido y a quienes comparten el saber.'],
      ['Usar internet como única forma de acceso a la actividad…',['Puede generar una barrera si no todas las personas tienen conectividad.','Nunca genera barreras.','Es obligatorio.'],0,'La difusión digital amplía alcance, pero no elimina la brecha de acceso.'],
      ['Explicar que una traducción aproximada no conserva todo el sentido cultural…',['Es una buena práctica.','Debe ocultarse.','Significa que traducir no sirve.'],0,'Reconocer límites de traducción evita presentar equivalencias falsas.'],
      ['Repetir un estereotipo para “hacer más divertido” un cartel…',['Favorece la diversidad.','Puede reforzar prejuicios y debe revisarse.','No tiene efectos.'],1,'La divulgación debe evitar caricaturizar culturas o hablantes.'] ]},
    len8:{id:'len8',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R8 · Arma el folleto',type:'lang-sequence',icon:'📄',desc:'Ordena la arquitectura de un folleto de divulgación lingüística para comunicar con claridad.',paper:'Cuaderno p. 25',items:['Definir propósito y público del folleto.','Seleccionar una práctica cultural o lingüística documentada.','Organizar información breve en secciones.','Redactar título, subtítulos y textos claros.','Incluir imágenes o dibujos con pie y créditos.','Incorporar palabras o fragmentos en otra lengua sólo después de verificarlos.','Añadir fuentes, créditos y una invitación a conocer o participar.','Revisar legibilidad, respeto cultural y versión final.']},
    len9:{id:'len9',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R9 · Traductor responsable',type:'lang-quiz',icon:'🤝',desc:'Toma decisiones cuidadosas al comunicar palabras, nombres y prácticas entre lenguas.',paper:'Cuaderno p. 26',qs:[
      ['No sabes con certeza cómo se escribe una palabra en una lengua de la comunidad. ¿Qué haces?',['La inventas fonéticamente.','La verificas con una persona hablante o una fuente confiable y acreditas el apoyo.','La omites para siempre.'],1,'Verificar evita errores y reconoce la autoridad de los hablantes.'],
      ['Una palabra no tiene equivalente exacto en español. ¿Qué conviene?',['Forzar una traducción.','Conservar el término y explicar brevemente su significado y contexto.','Cambiarla por cualquier palabra.'],1,'Algunos términos condensan significados culturales que no se trasladan literalmente.'],
      ['¿Qué frase es más respetuosa?',['“Hablan raro”.','“Esta comunidad usa una lengua con historia, variantes y prácticas propias”.','“Su lengua está atrasada”.'],1,'El lenguaje de divulgación debe informar sin jerarquizar ni ridiculizar.'],
      ['Si una persona comparte un saber comunitario para tu folleto…',['puedes publicarlo sin avisar.','conviene acordar cómo citarlo y qué información sí puede difundirse.','debes cambiar su relato.'],1,'El consentimiento y el crédito son parte de una divulgación responsable.'],
      ['Una traducción fue hecha por un compañero bilingüe. ¿Qué debes hacer?',['Reconocer su colaboración y revisar juntos el sentido.','Borrar su nombre.','Presentarla como traducción automática.'],0,'Dar crédito reconoce el trabajo lingüístico y permite revisar el significado.'] ]},
    len10:{id:'len10',field:'lenguajes',fieldTitle:'Lenguajes · PPA 1',title:'R10 · Pasaporte final',type:'lang-quiz',icon:'🎫',desc:'Reto integrador: conecta debate, exposición y folleto con diversidad lingüística y cultural.',paper:'Cuaderno p. 29',qs:[
      ['¿Qué une mejor los tres productos del PPA?',['Competir por el diseño más llamativo.','Investigar, comunicar y valorar la diversidad mediante argumentos, arte y divulgación.','Copiar información sin discutirla.'],1,'Los tres productos buscan reconocer y valorar diversidad cultural y lingüística.'],
      ['Un argumento pierde fuerza cuando…',['no puede rastrearse la evidencia que lo sostiene.','incluye una fuente pertinente.','reconoce un límite.'],0,'La rastreabilidad permite revisar el fundamento.'],
      ['Una exposición pluricultural es más sólida cuando…',['muestra varias perspectivas con contexto y evita estereotipos.','presenta culturas como curiosidades.','no permite preguntas.'],0,'La pluriculturalidad exige representación contextualizada y respetuosa.'],
      ['Un folleto bilingüe o multilingüe debe…',['verificar la lengua y acreditar apoyos o fuentes.','traducir literalmente todo aunque pierda sentido.','inventar palabras para completar.'],0,'La claridad y la verificación son esenciales.'],
      ['¿Qué acción favorece la revitalización lingüística?',['Ampliar usos de la lengua en espacios escolares y comunitarios con participación de hablantes.','Prohibirla en actividades públicas.','Usarla sólo como adorno.'],0,'La revitalización implica uso, transmisión y reconocimiento.'],
      ['Si el público cuestiona una idea de tu equipo…',['escucha, responde con evidencia y ajusta si es necesario.','descalifica la pregunta.','termina la presentación.'],0,'La retroalimentación ayuda a mejorar argumentos y productos.'] ]}
  });

  let tvField = localStorage.getItem('televerso_active_field') || 'lenguajes';
  const originalRenderDashboard = renderStudentDashboard;
  const originalLaunchMission = launchMission;

  function ensureFieldUI(){
    const view=document.getElementById('view-student'); if(!view||document.getElementById('tv-field-selector')) return;
    const badgeHeading=[...view.querySelectorAll('h4')].find(h=>h.textContent.includes('Insignias Cooperativas'));
    const badgeBlock=badgeHeading?.parentElement;
    if(badgeBlock) badgeBlock.id='tv-badges-ens';
    const selector=document.createElement('div'); selector.id='tv-field-selector'; selector.className='glass-panel p-5 rounded-3xl border border-white/10';
    selector.innerHTML=`<h4 class="text-sm font-black text-slate-300 uppercase tracking-wider mb-3 flex items-center gap-2"><i class="fa-solid fa-layer-group text-indigo-400"></i> Campos formativos</h4><div class="grid grid-cols-1 sm:grid-cols-2 gap-3"><button id="tv-btn-ens" onclick="tvSetField('ens')" class="p-4 rounded-2xl text-left bg-slate-800/80 hover:bg-slate-700 border border-white/10 transition"><span class="block text-xs font-black uppercase tracking-wider text-emerald-300">Campo formativo</span><strong class="block text-white mt-1">Ética, Naturaleza y Sociedades</strong></button><button id="tv-btn-leng" onclick="tvSetField('lenguajes')" class="p-4 rounded-2xl text-left bg-slate-800/80 hover:bg-slate-700 border border-white/10 transition"><span class="block text-xs font-black uppercase tracking-wider text-fuchsia-300">Campo formativo</span><strong class="block text-white mt-1">Lenguajes · PPA 1</strong><span class="block text-[11px] text-slate-400 mt-1">Voces que cuentan</span></button></div>`;
    badgeBlock?.before(selector);
    if(badgeBlock){
      const lb=document.createElement('div'); lb.id='tv-badges-leng'; lb.className='hidden';
      lb.innerHTML=`<h4 class="text-sm font-black text-slate-300 uppercase tracking-wider mb-3 flex items-center gap-2"><i class="fa-solid fa-award text-fuchsia-400"></i> Insignias Cooperativas · Lenguajes</h4><div class="grid grid-cols-1 sm:grid-cols-3 gap-4"><div id="tv-badge-voice" class="glass-card p-4 rounded-2xl opacity-50 flex items-center gap-3.5"><div class="w-12 h-12 rounded-xl bg-indigo-500/20 flex items-center justify-center text-2xl">🎙️</div><div><strong class="text-white text-sm block">Voz argumentada</strong><span class="text-[11px] text-slate-400">Argumenta y responde con evidencia.</span></div></div><div id="tv-badge-curator" class="glass-card p-4 rounded-2xl opacity-50 flex items-center gap-3.5"><div class="w-12 h-12 rounded-xl bg-fuchsia-500/20 flex items-center justify-center text-2xl">🎨</div><div><strong class="text-white text-sm block">Curador pluricultural</strong><span class="text-[11px] text-slate-400">Representa con contexto y respeto.</span></div></div><div id="tv-badge-div" class="glass-card p-4 rounded-2xl opacity-50 flex items-center gap-3.5"><div class="w-12 h-12 rounded-xl bg-amber-500/20 flex items-center justify-center text-2xl">📣</div><div><strong class="text-white text-sm block">Divulgador lingüístico</strong><span class="text-[11px] text-slate-400">Comunica con verificación y crédito.</span></div></div></div>`;
      badgeBlock.after(lb);
    }
  }

  window.tvSetField=function(field){tvField=field;localStorage.setItem('televerso_active_field',field);renderStudentMissionsGrid();if(activeStudent)renderStudentDashboard();};

  renderStudentMissionsGrid=function(){
    ensureFieldUI();
    const c=document.getElementById('student-missions-grid'); if(!c)return;
    const missions=Object.values(missionCatalog).filter(m=>(m.field||'ens')===tvField);
    const heading=c.previousElementSibling;if(heading&&heading.tagName==='H4')heading.innerHTML=`<i class="fa-solid fa-list-check text-indigo-400"></i> ${tvField==='lenguajes'?'Lenguajes · PPA 1':'Ética, Naturaleza y Sociedades'} · ${missions.length} retos`;
    c.innerHTML=missions.map((m,i)=>`<div class="glass-card p-5 rounded-3xl flex flex-col justify-between border-t-2 ${tvField==='lenguajes'?'border-t-fuchsia-500':'border-t-indigo-500'}"><div><div class="flex justify-between items-center mb-3"><span class="px-2.5 py-0.5 bg-indigo-500/20 text-indigo-300 text-[10px] font-black uppercase rounded-lg border border-indigo-500/30">Misión ${i+1}</span><i id="badge-mission-${m.id}" class="fa-solid fa-lock text-slate-500 text-base"></i></div><h4 class="text-base font-bold text-white mb-1.5">${m.icon} ${m.title}</h4><p class="text-slate-300 text-xs ${m.paper?'mb-2':'mb-4'} leading-relaxed">${m.desc}</p>${m.paper?`<p class="text-amber-300/90 text-[11px] font-semibold mb-4">✏️ Actividad equivalente: ${m.paper}</p>`:''}</div><button onclick="launchMission('${m.id}')" class="w-full py-2.5 ${tvField==='lenguajes'?'bg-fuchsia-600 hover:bg-fuchsia-500':'bg-indigo-600 hover:bg-indigo-500'} text-white font-bold rounded-xl text-xs transition"><i class="fa-solid fa-play mr-1"></i> Iniciar Reto</button></div>`).join('');
    const ens=document.getElementById('tv-badges-ens'),lng=document.getElementById('tv-badges-leng');if(ens)ens.classList.toggle('hidden',tvField!=='ens');if(lng)lng.classList.toggle('hidden',tvField!=='lenguajes');
    ['tv-btn-ens','tv-btn-leng'].forEach(id=>document.getElementById(id)?.classList.remove('ring-2','ring-indigo-400','bg-indigo-950/50'));document.getElementById(tvField==='lenguajes'?'tv-btn-leng':'tv-btn-ens')?.classList.add('ring-2','ring-indigo-400','bg-indigo-950/50');
  };

  renderStudentDashboard=function(){
    renderStudentMissionsGrid(); originalRenderDashboard();
    const comp=activeStudent?.completed||{};Object.values(missionCatalog).filter(m=>(m.field||'ens')===tvField).forEach(m=>{const b=document.getElementById(`badge-mission-${m.id}`);if(b)b.className=comp[m.id]?'fa-solid fa-circle-check text-emerald-400 text-base':'fa-solid fa-lock text-slate-500 text-base';});
    [['tv-badge-voice',['len1','len2','len3']],['tv-badge-curator',['len4','len5','len6']],['tv-badge-div',['len7','len8','len9','len10']]].forEach(([id,keys])=>document.getElementById(id)?.classList.toggle('opacity-50',!keys.every(k=>comp[k])));
  };

  launchMission=function(id){const m=missionCatalog[id];if(!m?.type?.startsWith('lang-'))return originalLaunchMission(id);activeMissionKey=id;missionGameState={};document.getElementById('modal-mission').classList.remove('hidden');if(m.type==='lang-classify')langClassify(m);if(m.type==='lang-quiz')langQuiz(m);if(m.type==='lang-memory')langMemory(m);if(m.type==='lang-sequence')langSequence(m);};
  const head=(m,p='')=>`<div class="flex justify-between gap-3 text-xs font-bold text-indigo-300"><span>${p}</span><span class="text-amber-300">✏️ ${m.paper}</span></div><h3 class="text-xl font-black text-white">${m.icon} ${m.title}</h3><p class="text-slate-300 text-xs">${m.desc}</p>`;

  function langClassify(m){missionGameState={list:[...m.items].sort(()=>Math.random()-.5),idx:0,hits:0,errors:0,details:[]};langClassRender();}
  function langClassRender(){const m=missionCatalog[activeMissionKey],s=missionGameState,a=document.getElementById('mission-content-area');if(s.idx>=s.list.length){saveMissionResults('¡Clasificación completada! Revisa una respuesta en tu cuaderno.');return;}const [text,ans,fb]=s.list[s.idx];a.innerHTML=`<div class="space-y-4 animate-pop">${head(m,`Reactivo ${s.idx+1} de ${s.list.length} · Aciertos: ${s.hits}`)}<div class="glass-card p-6 rounded-2xl text-center"><p class="text-base sm:text-lg font-semibold">${text}</p></div><div class="grid grid-cols-1 sm:grid-cols-3 gap-3">${m.cats.map((x,i)=>`<button onclick="langClassAnswer(${i})" class="p-3.5 bg-slate-800 hover:bg-fuchsia-600 rounded-xl font-bold text-xs sm:text-sm">${x}</button>`).join('')}</div></div>`;window._lc={ans,fb,text};}
  window.langClassAnswer=function(i){const m=missionCatalog[activeMissionKey],s=missionGameState,ok=i===window._lc.ans;ok?s.hits++:s.errors++;s.details.push({statement:window._lc.text,selected:m.cats[i],expected:m.cats[window._lc.ans],isCorrect:ok,explanation:window._lc.fb});Swal.fire({icon:ok?'success':'info',title:ok?'¡Correcto!':'Revisa tu clasificación',text:window._lc.fb,confirmButtonText:'Continuar'}).then(()=>{s.idx++;langClassRender();});};

  function langQuiz(m){missionGameState={idx:0,hits:0,errors:0,details:[]};langQuizRender();}
  function langQuizRender(){const m=missionCatalog[activeMissionKey],s=missionGameState,a=document.getElementById('mission-content-area');if(s.idx>=m.qs.length){saveMissionResults('¡Reto completado! Usa la retroalimentación para mejorar tu evidencia en el cuaderno.');return;}const [q,opts]=m.qs[s.idx];a.innerHTML=`<div class="space-y-4 animate-pop">${head(m,`Reactivo ${s.idx+1} de ${m.qs.length} · Aciertos: ${s.hits}`)}<div class="glass-card p-6 rounded-2xl"><p class="text-base sm:text-lg font-semibold mb-4">${q}</p><div class="grid gap-3">${opts.map((o,i)=>`<button onclick="langQuizAnswer(${i})" class="p-3.5 text-left bg-slate-800 hover:bg-fuchsia-600 rounded-xl font-bold text-xs sm:text-sm">${o}</button>`).join('')}</div></div><p class="text-slate-400 text-[11px] italic">No se califica la rapidez.</p></div>`;}
  window.langQuizAnswer=function(i){const m=missionCatalog[activeMissionKey],s=missionGameState,[q,opts,ans,fb]=m.qs[s.idx],ok=i===ans;ok?s.hits++:s.errors++;s.details.push({statement:q,selected:opts[i],expected:opts[ans],isCorrect:ok,explanation:fb});Swal.fire({icon:ok?'success':'info',title:ok?'¡Bien razonado!':'Revisa tu decisión',text:fb,confirmButtonText:'Continuar'}).then(()=>{s.idx++;langQuizRender();});};

  function langMemory(m){let deck=[];m.pairs.forEach((p,i)=>{deck.push({p:i,t:p[0]},{p:i,t:p[1]});});missionGameState={deck:deck.sort(()=>Math.random()-.5),flipped:[],matched:[],hits:0,errors:0,details:[]};langMemoryRender();}
  function langMemoryRender(){const m=missionCatalog[activeMissionKey],s=missionGameState,a=document.getElementById('mission-content-area');if(s.matched.length===s.deck.length){saveMissionResults('¡Memorama completado! Explica dos parejas en tu cuaderno.');return;}a.innerHTML=`<div class="space-y-4 animate-pop">${head(m,`Parejas: ${s.matched.length/2}/${m.pairs.length}`)}<div class="grid grid-cols-2 sm:grid-cols-4 gap-2.5">${s.deck.map((c,i)=>{const show=s.flipped.includes(i)||s.matched.includes(i);return`<div onclick="langMemFlip(${i})" class="memcard glass-card rounded-2xl p-2.5 flex items-center justify-center text-center select-none ${s.matched.includes(i)?'opacity-40 pointer-events-none':''}">${show?`<span class="text-xs font-bold">${c.t}</span>`:'<i class="fa-solid fa-brain text-2xl text-fuchsia-400"></i>'}</div>`;}).join('')}</div></div>`;}
  window.langMemFlip=function(i){const s=missionGameState;if(s.flipped.length>=2||s.flipped.includes(i)||s.matched.includes(i))return;s.flipped.push(i);langMemoryRender();if(s.flipped.length===2){const[a,b]=s.flipped,c1=s.deck[a],c2=s.deck[b];if(c1.p===c2.p){s.hits++;s.matched.push(a,b);s.details.push({statement:`Pareja: ${c1.t}`,selected:c2.t,expected:c2.t,isCorrect:true,explanation:'Emparejamiento correcto.'});s.flipped=[];setTimeout(langMemoryRender,250);}else{s.errors++;setTimeout(()=>{s.flipped=[];langMemoryRender();},850);}}};

  function langSequence(m){missionGameState={items:[...m.items].sort(()=>Math.random()-.5),hits:0,errors:0,details:[]};langSeqRender();}
  function langSeqRender(){const m=missionCatalog[activeMissionKey],s=missionGameState,a=document.getElementById('mission-content-area');a.innerHTML=`<div class="space-y-4 animate-pop">${head(m,`Ordena ${m.items.length} pasos`)}<div class="space-y-2">${s.items.map((x,i)=>`<div class="glass-card p-3 rounded-xl flex items-center gap-3"><span class="w-7 h-7 rounded-lg bg-fuchsia-500/20 text-fuchsia-300 flex items-center justify-center font-black text-xs">${i+1}</span><span class="flex-1 text-sm font-semibold">${x}</span><button onclick="langSeqMove(${i},-1)" class="px-2.5 py-2 bg-slate-800 rounded-lg">▲</button><button onclick="langSeqMove(${i},1)" class="px-2.5 py-2 bg-slate-800 rounded-lg">▼</button></div>`).join('')}</div><button onclick="langSeqCheck()" class="w-full py-3 bg-emerald-600 hover:bg-emerald-500 text-white font-black rounded-xl">Comprobar orden</button></div>`;}
  window.langSeqMove=function(i,d){const s=missionGameState,j=i+d;if(j<0||j>=s.items.length)return;[s.items[i],s.items[j]]=[s.items[j],s.items[i]];langSeqRender();};
  window.langSeqCheck=function(){const m=missionCatalog[activeMissionKey],s=missionGameState;let n=0;s.items.forEach((x,i)=>{if(x===m.items[i])n++;});if(n===m.items.length){s.hits=n;s.details=m.items.map((x,i)=>({statement:`Paso ${i+1}`,selected:x,expected:x,isCorrect:true,explanation:'Posición correcta.'}));saveMissionResults('¡Secuencia completada! Lleva este orden al cuaderno.');}else{const wrong=m.items.length-n;s.errors+=wrong;Swal.fire({icon:'info',title:'Aún hay pasos por ajustar',text:`Tienes ${n} de ${m.items.length} pasos en su posición esperada.`,confirmButtonText:'Seguir ordenando'});}};

  // El complemento se carga antes de que se dispare DOMContentLoaded; la llamada original
  // a renderStudentMissionsGrid ya utilizará la versión ampliada definida arriba.
})();
