import {onAuthStateChanged,signInWithEmailAndPassword,signOut} from "https://www.gstatic.com/firebasejs/11.3.1/firebase-auth.js";
import {httpsCallable} from "https://www.gstatic.com/firebasejs/11.3.1/firebase-functions.js";
import {auth,functions} from "./firebase.js";
import * as D from "./data.js";
import {can,canAccessGroup} from "./permissions.js";
import {$,$$,esc,toast,table,statusBadge,openForm,confirmAction,bindDialogClose,empty} from "./ui.js";

const S={profile:null,school:null,cycles:[],cycle:null,groups:[],students:[],teachers:[],activities:[],route:"dashboard"};
const NAV=[["dashboard","Panel principal","escuela.ver"],["students","Alumnos","alumnos.ver"],["teachers","Docentes","docentes.ver"],["groups","Grupos","grupos.ver"],["attendance","Asistencias","asistencias.ver"],["activities","Actividades","actividades.ver"],["grades","Calificaciones","calificaciones.ver"],["documents","Documentos","documentos.ver"],["cycles","Ciclos escolares","ciclos.ver"],["users","Usuarios","usuarios.ver"],["license","Licencia","configuracion.ver"]];
bindDialogClose();
$("#login-form").onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$("#login-email").value.trim(),$("#login-password").value)}catch(x){$("#login-error").hidden=false;$("#login-error").textContent="Correo o contraseña incorrectos."}};
$("#logout-btn").onclick=()=>signOut(auth);window.addEventListener("online",()=>network(true));window.addEventListener("offline",()=>network(false));

onAuthStateChanged(auth,async u=>{if(!u)return login();try{const p=await D.getUserProfile(u.uid);if(!p||p.active===false)throw Error("Perfil no autorizado");Object.assign(p,{uid:u.uid,email:u.email});S.profile=p;D.setSessionContext(p);S.school=await D.getSchool();S.cycles=await D.list("cycles");const id=S.school?.activeCycleId||S.cycles.find(x=>x.active)?.id||S.cycles[0]?.id;S.cycle=S.cycles.find(x=>x.id===id)||null;D.setActiveCycleId(S.cycle?.id||null);await refresh();app();nav();cyclesSelect();go("dashboard")}catch(x){toast(x.message,"error")}});
function login(){$("#login-view").hidden=false;$("#app-view").hidden=true}
function app(){$("#login-view").hidden=true;$("#app-view").hidden=false;$("#school-name-side").textContent=S.school?.name||"Plantel";$("#user-display").textContent=S.profile.displayName||S.profile.email;$("#user-role").textContent=S.profile.role;network(navigator.onLine)}
function network(v){$("#connection-dot").className=`dot ${v?"online":"offline"}`;$("#connection-label").textContent=v?"Firebase conectado":"Modo sin conexión"}
function nav(){$("#main-nav").innerHTML=NAV.filter(x=>can(S.profile,x[2])).map(x=>`<button class="nav-btn" data-r="${x[0]}">${x[1]}</button>`).join("");$("#main-nav").onclick=e=>e.target.dataset.r&&go(e.target.dataset.r)}
function cyclesSelect(){$("#cycle-selector").innerHTML=S.cycles.map(c=>`<option value="${c.id}" ${c.id===S.cycle?.id?"selected":""}>${esc(c.name)}</option>`).join("");$("#cycle-selector").onchange=async e=>{S.cycle=S.cycles.find(c=>c.id===e.target.value);D.setActiveCycleId(S.cycle.id);await refresh();render()}}
function go(r){S.route=r;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.r===r));render()}
function head(t,s=""){$("#page-title").textContent=t;$("#page-subtitle").textContent=s}
async function scoped(name){if(!S.cycle)return[];if(["Administrador","Control Escolar"].includes(S.profile.role))return D.list(name,{cycle:true});const ids=(S.profile.allowedGroupIds||[]).slice(0,30);return ids.length?D.list(name,{cycle:true,where:[["groupId","in",ids]]}):[]}
async function refresh(){[S.groups,S.students,S.activities]=await Promise.all([S.cycle?D.list("groups",{cycle:true}):[],scoped("students"),scoped("activities")]);S.teachers=can(S.profile,"docentes.ver")?await D.list("teachers"):[]}
const groups=()=>S.groups.filter(g=>canAccessGroup(S.profile,g.id));const gn=id=>{const g=S.groups.find(x=>x.id===id);return g?`${g.grade}° ${g.name} · ${g.shift||""}`:"—"};const sn=s=>[s.lastName1,s.lastName2,s.firstName].filter(Boolean).join(" ");const tn=t=>[t.lastName1,t.lastName2,t.firstName].filter(Boolean).join(" ");
async function render(){const M={dashboard,students,teachers,groupsPage,attendance,activities,grades,documents,cyclesPage,users,license};await (M[S.route]||dashboard)()}

async function dashboard(){head("Panel principal",`Ciclo ${S.cycle?.name||"sin seleccionar"}`);const a=await scoped("attendance"),p=a.filter(x=>x.status==="Presente").length;$("#content").innerHTML=`<div class="grid-cards"><div class="metric-card"><div class="label">Alumnos</div><div class="metric">${S.students.length}</div></div><div class="metric-card"><div class="label">Grupos</div><div class="metric">${groups().length}</div></div><div class="metric-card"><div class="label">Docentes</div><div class="metric">${S.teachers.length}</div></div><div class="metric-card"><div class="label">Asistencia</div><div class="metric">${a.length?Math.round(p*100/a.length):0}%</div></div></div><div class="panel" style="margin-top:16px"><dl class="kv"><dt>Plantel</dt><dd>${esc(S.school.name||"")}</dd><dt>CCT</dt><dd>${esc(S.school.cct||"")}</dd><dt>Usuario</dt><dd>${esc(S.profile.displayName||S.profile.email)}</dd><dt>Rol</dt><dd>${esc(S.profile.role)}</dd></dl></div>`}

function crud({title,sub,col,rows,perm,cols,fields,prepare=(x=>x),after=refresh}){head(title,sub);const draw=()=>{$("#entity-table").innerHTML=table([...cols,{label:"Acciones",render:r=>`<div class="actions">${can(S.profile,`${perm}.editar`)?`<button class="btn ghost small" data-e="${r.id}">Editar</button>`:""}${can(S.profile,`${perm}.eliminar`)?`<button class="btn danger small" data-d="${r.id}">Eliminar</button>`:""}</div>`}],rows)};$("#content").innerHTML=`<div class="panel"><div class="toolbar"><div></div><div>${can(S.profile,`${perm}.crear`)?'<button id="new-entity" class="btn primary">Nuevo registro</button>':''}</div></div><div id="entity-table"></div></div>`;draw();const edit=r=>openForm({title:r.id?`Editar ${title}`:`Nuevo ${title}`,fields:fields(),record:r,onSave:async x=>{x=prepare(x,r);if(r.id)await D.save(col,r.id,x);else await D.create(col,x);toast("Registro guardado","success");await after();render()}});$("#new-entity")?.addEventListener("click",()=>edit({}));$("#entity-table").onclick=async e=>{const id=e.target.dataset.e||e.target.dataset.d;if(!id)return;const r=rows.find(x=>x.id===id);if(e.target.dataset.e)edit(r);else if(await confirmAction("Eliminar registro","El registro se enviará a la papelera.")){await D.remove(col,id,title);await after();render()}}}
function groupOpts(){return [{value:"",label:"Seleccionar..."},...groups().map(g=>({value:g.id,label:gn(g.id)}))]}

async function students(){crud({title:"Alumnos",sub:"Expediente básico y grupo",col:"students",rows:S.students,perm:"alumnos",cols:[{label:"Matrícula",key:"enrollment"},{label:"Alumno",render:r=>`<strong>${esc(sn(r))}</strong><br>${esc(r.curp||"")}`},{label:"Grupo",render:r=>esc(gn(r.groupId))},{label:"Tutor",key:"guardianName"}],fields:()=>[{name:"enrollment",label:"Matrícula",required:true},{name:"curp",label:"CURP",required:true},{name:"firstName",label:"Nombre(s)",required:true},{name:"lastName1",label:"Apellido paterno",required:true},{name:"lastName2",label:"Apellido materno"},{name:"groupId",label:"Grupo",type:"select",required:true,options:groupOpts()},{name:"academicStatus",label:"Estado",type:"select",options:["Activo","Baja temporal","Baja definitiva","Egresado"]},{name:"guardianName",label:"Tutor",required:true},{name:"guardianPhone",label:"Teléfono tutor"},{name:"address",label:"Domicilio",wide:true},{name:"allergies",label:"Alergias",wide:true}],prepare:x=>{if(!canAccessGroup(S.profile,x.groupId))throw Error("Grupo fuera de alcance");return x}})}
async function teachers(){crud({title:"Docentes",sub:"Personal y grupos asignados",col:"teachers",rows:S.teachers,perm:"docentes",cols:[{label:"Clave",key:"employeeCode"},{label:"Docente",render:r=>esc(tn(r))},{label:"Correo",key:"email"},{label:"Puesto",key:"position"}],fields:()=>[{name:"employeeCode",label:"Clave",required:true},{name:"curp",label:"CURP",required:true},{name:"firstName",label:"Nombre(s)",required:true},{name:"lastName1",label:"Apellido paterno"},{name:"lastName2",label:"Apellido materno"},{name:"rfc",label:"RFC"},{name:"position",label:"Puesto"},{name:"email",label:"Correo",type:"email"},{name:"phone",label:"Teléfono"},{name:"assignedGroupIdsCsv",label:"IDs de grupos separados por coma",wide:true}],prepare:(x,r)=>{x.assignedGroupIds=(x.assignedGroupIdsCsv||"").split(",").map(v=>v.trim()).filter(Boolean);delete x.assignedGroupIdsCsv;return x}})}
async function groupsPage(){crud({title:"Grupos",sub:"Grado, turno, capacidad y tutor",col:"groups",rows:groups(),perm:"grupos",cols:[{label:"Grado",render:r=>`${r.grade}°`},{label:"Grupo",key:"name"},{label:"Turno",key:"shift"},{label:"Capacidad",key:"capacity"},{label:"Alumnos",render:r=>S.students.filter(s=>s.groupId===r.id).length}],fields:()=>[{name:"grade",label:"Grado",type:"number",min:1,max:6,required:true},{name:"name",label:"Grupo",required:true},{name:"shift",label:"Turno",type:"select",options:["Matutino","Vespertino"]},{name:"capacity",label:"Capacidad",type:"number"},{name:"tutorId",label:"Tutor",type:"select",options:[{value:"",label:"Sin asignar"},...S.teachers.map(t=>({value:t.id,label:tn(t)}))]}]})}
async function activities(){crud({title:"Actividades",sub:"Trabajos y ponderaciones",col:"activities",rows:S.activities,perm:"actividades",cols:[{label:"Actividad",key:"name"},{label:"Grupo",render:r=>esc(gn(r.groupId))},{label:"Materia",key:"subject"},{label:"Tipo",key:"workType"},{label:"Periodo",key:"period"}],fields:()=>[{name:"groupId",label:"Grupo",type:"select",required:true,options:groupOpts()},{name:"subject",label:"Materia",required:true},{name:"workType",label:"Tipo",type:"select",options:["Tarea","Trabajo en clase","Examen","Proyecto"]},{name:"weight",label:"Ponderación %",type:"number",min:0,max:100},{name:"period",label:"Periodo",type:"number",min:1,max:3},{name:"academicProject",label:"Proyecto académico",type:"number"},{name:"name",label:"Actividad",required:true,wide:true}],prepare:x=>{if(!canAccessGroup(S.profile,x.groupId))throw Error("Grupo fuera de alcance");return x}})}

async function attendance(){head("Asistencias","Captura diaria por grupo");$("#content").innerHTML=`<div class="panel"><div class="toolbar"><div class="toolbar-left"><select id="ag"><option value="">Grupo</option>${groups().map(g=>`<option value="${g.id}">${esc(gn(g.id))}</option>`).join("")}</select><input id="ad" type="date" value="${new Date().toISOString().slice(0,10)}"></div><button id="as" class="btn primary">Guardar</button></div><div id="alist">${empty("Selecciona un grupo")}</div></div>`;let marks={};const load=async()=>{const gid=$("#ag").value,date=$("#ad").value;if(!gid)return;const st=S.students.filter(s=>s.groupId===gid),ex=await D.list("attendance",{cycle:true,where:[["groupId","==",gid],["date","==",date]]});marks=Object.fromEntries(st.map(s=>[s.id,ex.find(a=>a.studentId===s.id)?.status||"Presente"]));$("#alist").innerHTML=`<div class="att-grid">${st.map(s=>`<div class="att-card"><strong>${esc(sn(s))}</strong><div class="segmented">${["Presente","Falta","Retardo","Justificada"].map(v=>`<button data-s="${s.id}" data-v="${v}" class="${marks[s.id]===v?"selected":""}">${v[0]}</button>`).join("")}</div></div>`).join("")}</div>`};$("#ag").onchange=load;$("#ad").onchange=load;$("#alist").onclick=e=>{const b=e.target.closest("[data-s]");if(!b)return;marks[b.dataset.s]=b.dataset.v;b.parentElement.querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x===b))};$("#as").onclick=async()=>{const gid=$("#ag").value,date=$("#ad").value;if(!gid)return toast("Selecciona grupo","error");const st=S.students.filter(s=>s.groupId===gid),ex=await D.list("attendance",{cycle:true,where:[["groupId","==",gid],["date","==",date]]});await D.bulkUpsert("attendance",st.map(s=>({id:ex.find(a=>a.studentId===s.id)?.id||`${date}_${s.id}`,data:{studentId:s.id,studentEnrollment:s.enrollment,groupId:gid,date,status:marks[s.id]||"Presente",cycleId:S.cycle.id}})));toast("Asistencia guardada","success")}}

async function grades(){head("Calificaciones","Captura por actividad");$("#content").innerHTML=`<div class="panel"><div class="toolbar"><div class="toolbar-left"><select id="gg"><option value="">Grupo</option>${groups().map(g=>`<option value="${g.id}">${esc(gn(g.id))}</option>`).join("")}</select><select id="ga"><option value="">Actividad</option></select></div><button id="gs" class="btn primary">Guardar</button></div><div id="glist">${empty("Selecciona grupo y actividad")}</div></div>`;let vals={};$("#gg").onchange=()=>{$("#ga").innerHTML='<option value="">Actividad</option>'+S.activities.filter(a=>a.groupId===$("#gg").value).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join("")};$("#ga").onchange=async()=>{const gid=$("#gg").value,aid=$("#ga").value;if(!aid)return;const st=S.students.filter(s=>s.groupId===gid),ex=await D.list("activityGrades",{cycle:true,where:[["groupId","==",gid],["activityId","==",aid]]});vals=Object.fromEntries(st.map(s=>[s.id,ex.find(g=>g.studentId===s.id)?.grade??""]));$("#glist").innerHTML=table([{label:"Matrícula",key:"enrollment"},{label:"Alumno",render:s=>esc(sn(s))},{label:"Calificación",render:s=>`<input data-g="${s.id}" type="number" min="0" max="10" step="0.1" value="${esc(vals[s.id])}" style="width:90px">`}],st)};$("#glist").oninput=e=>e.target.dataset.g&&(vals[e.target.dataset.g]=e.target.value);$("#gs").onclick=async()=>{const gid=$("#gg").value,aid=$("#ga").value;if(!gid||!aid)return;const act=S.activities.find(a=>a.id===aid),st=S.students.filter(s=>s.groupId===gid),ex=await D.list("activityGrades",{cycle:true,where:[["groupId","==",gid],["activityId","==",aid]]});await D.bulkUpsert("activityGrades",st.filter(s=>vals[s.id]!=="").map(s=>({id:ex.find(g=>g.studentId===s.id)?.id||`${aid}_${s.id}`,data:{studentId:s.id,studentEnrollment:s.enrollment,groupId:gid,activityId:aid,subject:act.subject,period:Number(act.period||1),grade:Number(vals[s.id]),gradedAt:new Date().toISOString().slice(0,10),cycleId:S.cycle.id}})));toast("Calificaciones guardadas","success")}}

async function documents(){head("Documentos","Incidencias y citatorios");const inc=await scoped("incidents"),cit=await scoped("summons");$("#content").innerHTML=`<div class="stack"><div class="panel"><div class="panel-head"><h3>Incidencias</h3><button id="ni" class="btn primary small">Nueva</button></div><div id="it">${table([{label:"Folio",key:"folio"},{label:"Fecha",key:"date"},{label:"Alumno",key:"studentName"},{label:"Tipo",key:"type"}],inc)}</div></div><div class="panel"><div class="panel-head"><h3>Citatorios</h3><button id="nc" class="btn primary small">Nuevo</button></div><div>${table([{label:"Folio",key:"folio"},{label:"Fecha cita",key:"appointmentDate"},{label:"Alumno",key:"studentName"},{label:"Tutor",key:"guardianName"},{label:"Estado",render:r=>statusBadge(r.status||"Pendiente",r.status==="Atendido"?"ok":"warn")}],cit)}</div></div></div>`;const so=()=>[{value:"",label:"Seleccionar..."},...S.students.map(s=>({value:s.id,label:`${s.enrollment} · ${sn(s)}`}))];$("#ni").onclick=()=>openForm({title:"Nueva incidencia",fields:[{name:"folio",label:"Folio",required:true},{name:"date",label:"Fecha",type:"date",required:true},{name:"studentId",label:"Alumno",type:"select",options:so(),required:true},{name:"type",label:"Tipo",required:true},{name:"description",label:"Descripción",type:"textarea",wide:true,required:true},{name:"actionsTaken",label:"Acciones",type:"textarea",wide:true}],onSave:async x=>{const s=S.students.find(v=>v.id===x.studentId);Object.assign(x,{studentName:sn(s),groupId:s.groupId,responsible:S.profile.displayName||S.profile.email});await D.create("incidents",x);render()}});$("#nc").onclick=()=>openForm({title:"Nuevo citatorio",fields:[{name:"folio",label:"Folio",required:true},{name:"appointmentDate",label:"Fecha cita",type:"date",required:true},{name:"appointmentTime",label:"Hora",type:"time"},{name:"studentId",label:"Alumno",type:"select",options:so(),required:true},{name:"reasonType",label:"Motivo",required:true},{name:"reasonDetail",label:"Detalle",type:"textarea",wide:true},{name:"status",label:"Estado",type:"select",options:["Pendiente","Atendido","Cancelado"]}],onSave:async x=>{const s=S.students.find(v=>v.id===x.studentId);Object.assign(x,{studentName:sn(s),guardianName:s.guardianName||"",groupId:s.groupId,responsible:S.profile.displayName||S.profile.email});await D.create("summons",x);render()}})}

async function cyclesPage(){head("Ciclos escolares","Fechas y ciclo activo");$("#content").innerHTML=`<div class="panel"><div class="toolbar"><div></div><button id="newc" class="btn primary">Nuevo ciclo</button></div><div id="ct">${table([{label:"Ciclo",key:"name"},{label:"Inicio",key:"startDate"},{label:"Fin",key:"endDate"},{label:"Estado",render:c=>c.id===S.cycle?.id?statusBadge("Activo","ok"):statusBadge("Inactivo")},{label:"Acciones",render:c=>c.id===S.cycle?.id?"":`<button class="btn success small" data-a="${c.id}">Activar</button>`}],S.cycles)}</div></div>`;$("#newc").onclick=()=>openForm({title:"Nuevo ciclo",fields:[{name:"name",label:"Nombre",required:true},{name:"startDate",label:"Inicio",type:"date"},{name:"endDate",label:"Fin",type:"date"}],onSave:async x=>{await D.create("cycles",x);S.cycles=await D.list("cycles");cyclesSelect();render()}});$("#ct").onclick=async e=>{if(!e.target.dataset.a)return;const c=S.cycles.find(x=>x.id===e.target.dataset.a);if(await confirmAction("Activar ciclo",c.name)){await D.setActiveCycle(c);S.cycle=c;D.setActiveCycleId(c.id);S.cycles=await D.list("cycles");cyclesSelect();await refresh();render()}}}

async function users(){head("Usuarios","Roles y alcance por grupos");let us=[];try{us=(await httpsCallable(functions,"listSchoolUsers")()).data.users||[]}catch{}$("#content").innerHTML=`<div class="stack"><div class="callout">Las cuentas se crean mediante Cloud Functions; el navegador no puede otorgarse privilegios.</div><div class="panel"><div class="toolbar"><div></div><button id="nu" class="btn primary">Nuevo usuario</button></div>${table([{label:"Nombre",key:"displayName"},{label:"Correo",key:"email"},{label:"Rol",key:"role"},{label:"Activo",render:u=>statusBadge(u.active===false?"No":"Sí",u.active===false?"danger":"ok")}],us)}</div></div>`;$("#nu").onclick=()=>openForm({title:"Crear usuario",fields:[{name:"displayName",label:"Nombre",required:true},{name:"email",label:"Correo",type:"email",required:true},{name:"password",label:"Contraseña temporal",type:"password",required:true},{name:"role",label:"Rol",type:"select",options:["Administrador","Control Escolar","Docente","Tutor","Finanzas"]},{name:"allowedGroupIdsCsv",label:"IDs de grupos permitidos",wide:true}],onSave:async x=>{x.allowedGroupIds=x.allowedGroupIdsCsv.split(",").map(v=>v.trim()).filter(Boolean);delete x.allowedGroupIdsCsv;await httpsCallable(functions,"adminCreateUser")(x);toast("Usuario creado","success");render()}})}

async function license(){head("Licencia","CCT, vigencia y equipos");let st={active:false};try{st=(await httpsCallable(functions,"getLicenseStatus")()).data}catch{}$("#content").innerHTML=`<div class="two-col"><div class="panel"><h3>Estado</h3><dl class="kv"><dt>Licencia</dt><dd>${st.active?"Activa":"Sin activar"}</dd><dt>Plan</dt><dd>${esc(st.plan||"—")}</dd><dt>Vigencia</dt><dd>${esc(st.expiresAt||"—")}</dd><dt>Equipos</dt><dd>${esc(st.devicesUsed??"—")} / ${esc(st.maxDevices??"—")}</dd></dl></div><div class="panel"><h3>Activar</h3><textarea id="lc" class="license-code" placeholder="Código de licencia"></textarea><button id="la" class="btn primary full">Activar licencia</button></div></div>`;$("#la").onclick=async()=>{let id=localStorage.getItem("AULACONTROL_DEVICE_ID");if(!id){id=crypto.randomUUID();localStorage.setItem("AULACONTROL_DEVICE_ID",id)}try{await httpsCallable(functions,"activateLicense")({code:$("#lc").value.trim(),deviceId:id});toast("Licencia activada","success");render()}catch(x){toast(x.message,"error")}}}
